# Generated by Django 3.2.4 on 2021-06-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BDTEC_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BD_text', models.CharField(max_length=200)),
                ('BD_date', models.DateTimeField(verbose_name='sensor data')),
            ],
        ),
    ]
